### ISSUE TITLE
Highlighting "#" and Arrows not Working 

### ISSUE THREAD

**Issue by bramses** [tbh1/sublime-notes#10]
Sublime 3083
Mac OS X Yosemite
Notes 1.0

Thanks!

**Comment by tbh1** [comment]
Any more details? What color scheme are you trying this with?
The syntax highlighting is based on TextMate definitions. While this plugin outlines how your editor should display different parts of the code (i.e. pounds and arrows), it's up to the creator of the your color scheme to actually display it.

**Comment by rybarova** [comment]
I have before same problem. The problem is with bad color scheme. I tried this with monokai. 
U must use another color scheme or edit monokai (if u use) and add

```
<dict>
	<key>scope</key>
	<string>variable.language, variable.parameter.function.language</string>
	<key>settings</key>
	<dict>
		<key>fontStyle</key>
		<string>italic</string>
		<key>foreground</key>
		<string>#1CFF7B</string>
		<key>background</key>
		<string></string>
	</dict>
</dict>
```
Thats work for me. I hope u understeand to my bad english. And I hope my solution is correct because i am newbie with sublime text 3.

**Comment by greyxray** [comment]
@rybarova what exactly is the file that is suggested to edit?
