### ISSUE TITLE
sublime crashes when editing .notes files

### ISSUE THREAD

**Issue by arricolor** [tbh1/sublime-notes#11]
When I enter words with German Umlauts, e.g. the word "hätte" in a .notes file the editor crashes without further notice. 
That is on OS X 10.10.5 and Sublime Build 3099

**Comment by tbh1** [comment]
I've been unable to reproduce this. Are you able to write umlauts in other syntax languages with the same color scheme?

**Comment by tbh1** [comment]
Unable to reproduce, please let me know if this is still an issue.
