### ISSUE TITLE
Error in console at start notes

### ISSUE THREAD

**Issue by rybarova** [tbh1/sublime-notes#12]
When I start notes I take two errors in my console. Can u help me fixt it? Thank you for your time nad nice package.

`Error loading scope:text.xml.xsl: Unable to find syntax file for scope text.xml.xsl in Packages/Notes/notes.tmLanguage
Error loading scope:source.postscript: Unable to find syntax file for scope source.postscript in Packages/Notes/notes.tmLanguage`

**Comment by tbh1** [comment]
It sounds like this is created by conflicting syntax plugins. Are you using any XML or postscript plugins?
Do you have anything listed in your `ignored_packages`?

**Comment by rybarova** [comment]
Thank you for superfast reply. I have ignored only "Vintage". I have Sublime text 3 portable version: 3103 on windows 10 x64. When I download clear sublime and download only your package "notes" problem/error is back. So I have problem/errors too without xml or postscript plugins. Do you have plan how I can fix it? Sorry for my bad english. I hope you understeand.

**Comment by tbh1** [comment]
Did some digging around -- looks like the XSL syntax was removed from default packages. Postscript is referenced from the default Perl package, which is a sublime bug. You can see this by opening a fresh sublime instance and changing to Perl syntax.

I'll remove XSL support, but I'm afraid there isn't much I can do about postscript other than dropping perl support. It shouldn't affect normal use.

**Comment by rybarova** [comment]
Thank you for your time. So these errors I can ignore?
```
Error loading scope:source.postscript: Unable to find syntax file for scope source.postscript in Packages/Notes/notes.tmLanguage
Error loading scope:source.postscript: Unable to find syntax file for scope source.postscript in Packages/Notes/tnotes.tmLanguage
```
That's only warning but normal using is not affected? Do you have any idea how I can repair this bug with default Perl package? On Google i can't find something useful. Probably now I must turn to ST3 support? Anyway thank you for your time and package.

**Comment by rybarova** [comment]
Here is solution: https://forum.sublimetext.com/t/error-loading-scope-postscript/19622

Download https://github.com/textmate/postscript.tmbundle/blob/master/Syntaxes/Postscript.tmLanguage
and give this file in here: Sublime:\\Data\Packages\User\

Now I have Notes without error. Thank you for your time and sorry for abusing.
