### ISSUE TITLE
Sublime crashes when opening a .notes file

### ISSUE THREAD

**Issue by G-Kevin** [tbh1/sublime-notes#14]
Hi,
this behavior appears since some dev builds and on the latest stable build.

Just opening a .notes file will crash Sublime, so there is no logging possible.

This is not the same issue as reported in #11, because it does not depend on any content.
Further, the file content isn't shown at all, you just see the loading bar and then Sublime will crash.

**Comment by bomis** [comment]
Having the same issue. With a little more details. I just updated to the latest version of sublime text. I uninstalled notes and installed again. seems to have fixed the crashing issue but it still hangs for several minutes before opening the .notes file.

**Comment by derek1906** [comment]
It doesn't crash on mine, but editing a .notes file occasionally lags and it takes a very long time to load the file.

**Comment by goralczyk** [comment]
Similar issue here. Last build (3114) made sublime unbearably slow when working with .notes. I'm on xubuntu 16.04.

**Comment by wesmattson** [comment]
Seeing this issue as well on 3114 from a mac on 10.11.3

**Comment by freb** [comment]
Same for me on build (3114) for Windows.

**Comment by tbh1** [comment]
Latest releases of ST3 seem to suffer CPU spikes when running regex over URLs. Even including the logic to highlight URLs seems to reproduce the issue. I've tested with multiple patterns and I believe it's related to sublime's ability to open URLs when right clicked. 

I've disabled URL highlighting which seems to fix the issue locally.
