### ISSUE TITLE
Sublime is really slow with files with notes syntax since the latest update of Sublime

### ISSUE THREAD

**Issue by DFelten** [tbh1/sublime-notes#15]
Sublime is really slow with files with notes syntax since the latest update of Sublime. After changing to an other syntax it's fast again. Especially on large files.

Tested on multiple machines with Windows 10 and Windows 7.

Notes: 1.0.3
Sublime Build 3114

**Comment by lgrn** [comment]
I'm having this issue as well. Confirmed as going away when removing the package, and it only affects .notes files.

**Comment by TCAllen07** [comment]
+1 for this problem. As @lgrn mentioned, it only affects files with Notes highlighting, though not necessary *.notes files only. In other words, even a small plain text file, unsaved or saved as a txt, etc., when told to highlight syntax as Notes, all slows to a crawl.

Notes: 1.0.3
Sublime Build 3114
MacBook Pro OS X Capitan 10.11.5

**Comment by TCAllen07** [comment]
I thought I'd try to see what changes may have caused the issue, so I downloaded various dev builds between 3103 & 3114. I thought I was on to something, witnessing the same slow-down in 3109 & 3106, but not in 3103 or 3104. But somewhere someway somehow the Notes package started responding normally again _in all builds_, including 3114. No clue how or why or if I'm just nuts, but I expect it has something to do with shared resources when using multiple ST3 apps simultaneously. I'll post back if I find anything.

**Comment by BuriedStPatrick** [comment]
Same problems here on Windows 10.
Problem disappears as soon as I switch syntax away from Notes, even in .notes files.
Even new small 5-line files take some time to load, showing the loading bar usually only present when opening very large files (at least on this machine). Baffingly, CPU usage doesn't seem to be affected, and general OS performance is seemingly unaffected.

Notes: 1.0.3
Sublime Build 3114
Windows 10 Pro x64

**Comment by bachhuberdesign** [comment]
Same issue as above

Notes: 1.0.3
Sublime Build 3114
Windows 10 Home x64

Hope this gets fixed as I love using this project for quick text notes but it spikes my CPU usage to 100% which makes it unusable.

**Comment by tbh1** [comment]
This appears to share a common cause with #14
