### ISSUE TITLE
Hotkey for block title?

### ISSUE THREAD

**Issue by JulianNorton** [tbh1/sublime-notes#2]
I didn't see an explanation for how to easily create block titles.

**Comment by toxicblu** [comment]
Currently there are no hotkeys for .notes. I will absolutely get on sublime snippets once the syntax is a bit more refined. In the meantime feel free to make a pull request.

To manually create block titles: just two lines of dashes with text between them.

**Comment by tbh1** [comment]
should now work when using `--- [tab]` in a .notes file
