### ISSUE TITLE
Cant find this package on package control. 

### ISSUE THREAD

**Issue by dopatraman** [tbh1/sublime-notes#3]
How do i install?

**Comment by toxicblu** [comment]
Hi, are you trying to install this in sublime text 2? It currently only supports ST3.

**Comment by netcell** [comment]
Trying to find it on ST3 here, no where to be found

**Comment by toxicblu** [comment]
Hey, mind if I ask what you searched for? It show as the top result for `notes` when I check.

**Comment by netcell** [comment]
Mine:
![screenshot 2015-09-16 11 58 59](https://cloud.githubusercontent.com/assets/3048558/9896709/554d6572-5c6a-11e5-9249-8ba22c2da9d8.png)

**Comment by erichuang0771** [comment]
try to add this repo as new channel in package control, works on mine, ST2

**Comment by tbh1** [comment]
I've added support for ST2, if this still doesn't appear in package control please open an issue with the official [package_control_channel](https://github.com/wbond/package_control_channel) repository.
