### ISSUE TITLE
I would suggest using only " for string highlighting

### ISSUE THREAD

**Issue by Garviell** [tbh1/sublime-notes#8]
When you are writing notes in english its quite bothersome to have it highlighted every time you have ' twice in a sentence.  I've been butchering my own grammar to work around this so far.

**Comment by tbh1** [comment]
Agreed. I'll remove support for single quoted strings.
Instead, you can now use double quotes or back ticks.

![image](https://cloud.githubusercontent.com/assets/5551627/14832059/4b11d1fe-0bc6-11e6-98d2-ec162fd54005.png)
